### ISSUE TITLE
Configure to use postgresql

### ISSUE THREAD

**Issue by fire** [mattermost/mattermost-operator#103]
There doesn't seem to be way to configure to use postgresql.

**Comment by cpanato** [comment]
Hello @fire 
today we only support Mysql as a builtin solution using the Mysql Operator.
to use Postgres you will need to spin an external Postgres and then create a secret with the connection string and when creating the Mattermost installation you set this in the manifest in the field: `Secret` under `Database`

you can see here: https://github.com/mattermost/mattermost-operator/blob/bae2543291b40e3e222b702038ed4d4dcd473ae9/pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go#L198

closing this issue, feel free to open a new one if you have any issues
