### ISSUE TITLE
size: xxxxXusers is not working when you want to scale

### ISSUE THREAD

**Issue by Born2Bake** [mattermost/mattermost-operator#123]
-----
**Begin Edit by @gabrieljackson** 

The Mattermost Operator currently offers two ways to set resources for the Mattermost app pods and supporting database and filestore pods. One method is to use the [Size](https://github.com/mattermost/mattermost-operator/blob/master/pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go#L29) configuration option and the other is to set the [Resources and Replicas](https://github.com/mattermost/mattermost-operator/blob/master/pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go#L30-L36) configuration.

`Size` configuration will set the `Resources` and `Replicas` configuration to some default values when used. By setting `Resources` and `Replicas`, users can override defaults set by the `Size` configuration.

This issue outlined below shows an issue with behavior where setting a given `Size` and then later changing it will not update the underlying `Resource` and `Replica` values. This is due to `Resource` and `Replica` overrides being possible as mentioned above.

A solution to this is desired where updating the `Size` value is able to scale the Mattermost application up or down in an intelligent way with respect to possible overrides.

If you're interested in working on this enhancement, please comment here and come join our "Contributors" community channel on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please join our "Developers" and "Developers: Cloud" community channels.

New contributors please see our Developer's Guide.

JIRA: https://mattermost.atlassian.net/browse/MM-22241
 
**End Edit**

-----

**Original Issue**

Hi,

> size: 5000users # Size of the Mattermost installation, typically based on the number of users. Automatically sets the replica and resource limits for Minio, databaes and app servers based on the number provided here. Accepts 100users, 1000users, 5000users, 10000users, or 25000users. Manually setting replicas or resources will override the values set by 'size'.

I am wondering, if size option is working only when you start mattermost first time. Thus, you cannot scale using that option afterwards? I started mattermost with 100users size so only 1 replica of everything was created. Then I changed the file to 5000users, applied config and nothing changed. Same goes if I decided to create mattermost to 10k users and then scale out to 100 - operator does not react on that. Could you explain what is the right way to set replicas if I need that? 

Thank you

**Comment by gabrieljackson** [comment]
Hello @Born2Bake,

Thanks for bringing this to our attention. You are correct that we do want the operator to scale mattermost installations up and down on demand.

I just tested this and your findings seem to be correct where sizeA -> sizeB does not properly update the underlying resource counts. We will look into this and correct it.

Keep in mind that the size values are always overridden by the specific resource and replica settings. i.e. if you change either of these the operator will scale up or down as requested.

https://github.com/mattermost/mattermost-operator/blob/master/pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go#L30-L36

The same thing goes for the database and minio spec settings.

**Comment by Szymongib** [comment]
Hi @gabrieljackson,
I was thinking that the `spec.Size` field could be treated as a write-only field. 

Setting the field would override Replicas and Resources to appropriate value no matter if they were set manually, but the field itself would not be preserved on the CR, therefore further overrides of Replicas or Resources would not be discarded and they would not be in conflict with the `spec.Size` field.

The Kubernetes leverages such behavior in for example Secrets, where `spec.StringData` field is a write-only field that on write is converted to `data` and no longer present on the Secret object.

Let me know what do you think about such approach!

**Comment by gabrieljackson** [comment]
@Szymongib, after thinking about this for a bit I am pretty sure it's a great solution!

It meets all of the criteria that I would be looking for:
1. By looking at the spec, I could see definitive values for the resources whether I had overridden any or not
2. Setting a new size would update all the values
3. Values could be manually tweaked after an initial size value was chosen.

I think this could really work well. What do you think @jwilander?

**Comment by jwilander** [comment]
I like that solution 👍 Only point I'd make is to make sure we document that field as write-only so that it's clear to users of the spec
