### ISSUE TITLE
Can I use this operator for Mattermost community installation?

### ISSUE THREAD

**Issue by gris-gris** [mattermost/mattermost-operator#140]

**Comment by cpanato** [comment]
Yes @gris-gris you can just change the `image` and the `version` in the spec

**Comment by mjrussell** [comment]
@cpanato is this true? I see the Cluster settings are set (which makes sense because it runs multiple replicas) but the docs seem to imply this setting is only available in enterprise plans https://docs.mattermost.com/configure/configuration-settings.html#high-availability

**Comment by cpanato** [comment]
@mjrussell you can use the community edition but not with HA, so you will have only one replica
