### ISSUE TITLE
Add owner reference to update-check job so that it points to Mattermost resource

### ISSUE THREAD

**Issue by Szymongib** [mattermost/mattermost-operator#215]
## Description

When modifying `spec.image` or `spec.version` of Mattermost resource the update-check job is run to ensure image is correct.
However, the job is not owned by the Mattermost resource which causes Operator to not to pick up when the job completes and carry on with update.

### Possible solution

Very simple and reliable solution would be to add `OwnerReference` to the job, so that it is owned by Mattermost resource.
We already have [function](https://github.com/mattermost/mattermost-operator/blob/272928435a67a730fe50583fee309a738c9d8536/pkg/resources/create_resources.go#L48) that adds owner references when creating objects. We could use it [when lunching the update job](https://github.com/mattermost/mattermost-operator/blob/272928435a67a730fe50583fee309a738c9d8536/pkg/resources/update_job.go#L19)

**Comment by imskrai** [comment]
Can I work on this? @Szymongib

**Comment by imskr** [comment]
Can I work on this @Szymongib ?

**Comment by imskr** [comment]
@Szymongib When setting up this repo locally and running command `make build-image kind-load-image deploy` I get following error:

```
go: added sigs.k8s.io/yaml v1.2.0
mv: rename /Users/shubhamkumar/go/src/github.com/mattermost/mattermost-operator/bin/controller-gen to /Users/shubhamkumar/go/src/github.com/mattermost/mattermost-operator/bin/controller-gen-v0.7.0: No such file or directory
make: *** [/Users/shubhamkumar/go/src/github.com/mattermost/mattermost-operator/bin/controller-gen] Error 1
```

**Comment by imskr** [comment]
@Szymongib I had a question:

1. To add the owner reference when launching job update can we simply `return` following [here](https://github.com/mattermost/mattermost-operator/blob/272928435a67a730fe50583fee309a738c9d8536/pkg/resources/update_job.go#L27) ?

```go
r.Create(owner, baseDeployment, reqLogger)
```

**Comment by imskr** [comment]
@Szymongib I have a question?

1. Can we directly call `LaunchMattermostUpdateJob` function [here](https://github.com/mattermost/mattermost-operator/blob/272928435a67a730fe50583fee309a738c9d8536/pkg/resources/create_resources.go#L59) ? so that the owner reference gets added

**Comment by Szymongib** [comment]
> When setting up this repo locally and running command make build-image kind-load-image deploy I get following error:

Does the `bin` directory exists? You might want to try creating it, but not sure if that will help, will need to look into it.

> Can we directly call LaunchMattermostUpdateJob function [here](https://github.com/mattermost/mattermost-operator/blob/272928435a67a730fe50583fee309a738c9d8536/pkg/resources/create_resources.go#L59) ? so that the owner reference gets added

I do not think so. The `Create` function is called in multiple different places for multiple different objects, we would not like to lunch a job each time it is called. You could however use the `ResourceHelper`s `Create` function to create and update job instead of directly using the Client [here](https://github.com/mattermost/mattermost-operator/blob/f8ac6ff1d21620a32ae99de2bef5df617bdd1f0f/pkg/resources/update_job.go#L25)

**Comment by imskr** [comment]
> > When setting up this repo locally and running command make build-image kind-load-image deploy I get following error:
> 
> Does the `bin` directory exists? You might want to try creating it, but not sure if that will help, will need to look into it.
> 
Yes it does in $GOPATH

> > Can we directly call LaunchMattermostUpdateJob function [here](https://github.com/mattermost/mattermost-operator/blob/272928435a67a730fe50583fee309a738c9d8536/pkg/resources/create_resources.go#L59) ? so that the owner reference gets added
> 
> I do not think so. The `Create` function is called in multiple different places for multiple different objects, we would not like to lunch a job each time it is called. You could however use the `ResourceHelper`s `Create` function to create and update job instead of directly using the Client [here](https://github.com/mattermost/mattermost-operator/blob/f8ac6ff1d21620a32ae99de2bef5df617bdd1f0f/pkg/resources/update_job.go#L25)

Thanks

**Comment by Szymongib** [comment]
Hey @imskr, there were some issues with scripts installing tooling. You can rebase with master and try again.

**Comment by imskr** [comment]
@Szymongib Thanks. I am getting following now when running `make build-image kind-load-image deploy`:

```
namespace/mattermost-operator configured
cd config/manager && /home/lucifer/go/bin/kustomize edit set image mattermost-operator="mattermost/mattermost-operator:test"
/bin/sh: line 1: /home/lucifer/go/bin/kustomize: No such file or directory
make: *** [Makefile:153: deploy] Error 127
```

**Comment by imskr** [comment]
Thanks @Szymongib
