### ISSUE TITLE
Add end-to-end test working with external database

### ISSUE THREAD

**Issue by Szymongib** [mattermost/mattermost-operator#216]
## Description

Current end-to-end tests of Mattermost Operator run using MySQL Operator and MinIO Operator. We should add another test which runs with an external database configuration.

This could be achieved by creating separate Postgres deployment on the Kind cluster on which the tests are run, and treat it as an external database.

Setting up of the deployment can be done either in bash script or in setup Go code.

We can also explore ways to test external file store in a similar way.

**Comment by imskr** [comment]
Can I work on this?

**Comment by Szymongib** [comment]
Hey @imskr,
I think this was actually done when we worked on other issue https://github.com/mattermost/mattermost-operator/tree/master/test/e2e-external.

I think however we could use some more test cases, specifically for Ingress configuration.

We could add another e2e test that would:
- Spin up Mattermost with some special Ingress configuration, ex. multiple hosts, some additional annotations and ingress class https://github.com/mattermost/mattermost-operator/blob/9d848b1f71e625f825f02108902f9566b1088c63/apis/mattermost/v1beta1/mattermost_types.go#L148
- We could then assert that all those things are properly set on the ingress
- As a next step we could update CR definition to disable the Ingress, and afterwards assert it was deleted by the Operator.

What do you think?

**Comment by imskr** [comment]
Sounds good to me. We can start working on this @Szymongib
