### ISSUE TITLE
Mattermost K8 / Reconciling State

### ISSUE THREAD

**Issue by unboxcoms** [mattermost/mattermost-operator#220]
Hi,

I followed the official documentation to deploy MM on K8s; however my installation process is stuck with custom resource state at "reconciling" 

<img width="753" alt="Screenshot 2021-02-13 at 9 24 01 PM" src="https://user-images.githubusercontent.com/61178409/107857556-dda7c500-6e54-11eb-91c1-dd6ab04df047.png">

**Comment by Szymongib** [comment]
Hi @unboxcoms, could you share your Mattermost manifest file and what is environment, k8s version etc. you are running on? Also Operator logs would be helpful, if you used `mattermost-operator` namespace for deploying the Operator you should be able to get them with this command:
```
kubectl -n mattermost-operator logs -l name=mattermost-operator
```

**Comment by Szymongib** [comment]
Resolved on Mattermost community.
The issue was caused by invalid database connection string.
