### ISSUE TITLE
Image pull secrets

### ISSUE THREAD

**Issue by mjnagel** [mattermost/mattermost-operator#221]
I have the Mattermost image hosted in private registry that requires authentication.

When building a Mattermost instance using the operator I don't see a way to provide my authentication (aka image pull secrets). 

If there is a way to either specify this secret or specify the service account to use for Mattermost which already exists, that would be a great help to me! If not, can we get this added? I'm working on v1.12.0.

**Comment by Szymongib** [comment]
Hi @mjnagel,
I am afraid it is not currently possible to specify `ImagePullSecrects` nor the `ServiceAccount`.
I do not see any problem with adding it tho.

Any thoughts @gabrieljackson?

**Comment by gabrieljackson** [comment]
Yep, I think this makes a ton of sense and would be great to have. We can create two help wanted tickets (pull secret and another for service account) to add this functionality.

**Comment by mjnagel** [comment]
Awesome, thanks @gabrieljackson and @Szymongib . I'll be tracking this issue and would love to be kept posted on updates.
