### ISSUE TITLE
Changing service type for Mattermost managed by Operator requires deleting service

### ISSUE THREAD

**Issue by Szymongib** [mattermost/mattermost-operator#244]
#### Summary
When changing the service type used by Mattermost with `useServiceLoadBalancer` either `true -> false` or `false -> true` the manual intervention of deleting the Service is required as some immutable fields change.

Mattermost Operator should be able to handle it either by doing smart update omitting immutable fields (if possible) or recreating the Service automatically.

#### Steps to reproduce

- Create any Mattermost instance with `useServiceLoadBalancer` set to `true`.
- Wait until Service is created.
- Edit Mattermost manifest setting `useServiceLoadBalancer` to `false`.

The reverse change (from `false` to `true`) also produces the error and should be handled properly.

#### Expected behavior
Service is updated and Mattermost reaches a `stable` state.

#### Observed behavior (that appears unintentional)
Mattermost is stuck in `reconciling` state and Mattermost Operator logs errors.

#### Possible fixes
Perform Service update omitting immutable fields (if possible) or recreate the Service automatically.

**Comment by MarkAndersonTrocme** [comment]
@gabrieljackson I'll take a look at this one

**Comment by gabrieljackson** [comment]
Awesome! Thanks for picking it up.
