### ISSUE TITLE
Local File store

### ISSUE THREAD

**Issue by felix-dpg** [mattermost/mattermost-operator#255]
#### Summary
Why in the CRD definition is not present Local File store?  Its not possible to deploy mattermost in k8s using the operator (or the helm chart) with local file store? 

In the docs say that is possible to use it: https://docs.mattermost.com/configure/configuration-settings.html#file-storage-system

#### Expected behavior
Use Local File store in the mattermost deployed in k8s.

**Comment by Szymongib** [comment]
In theory, it would be possible to configure local file store with environment variables. This is not possible with CRD tho, as containers file system is transient therefore unless you mount a persistent volume you would lose all your data whenever containers restart.

**Comment by felix-dpg** [comment]
Yes, I will mount a persistent volume, so, please, where in the docs talk about local file store with env variable?

**Comment by Szymongib** [comment]
We only recently added support for volumes and using external file store is more aligned with cloud application. Also as you mentioned there is always option for deploying Minio so I suppose there was never real need for it.

**Comment by gabrieljackson** [comment]
Due to a few recent requests for this functionality in other communication channels we are opening this up as a help wanted request.

The task would be to provide a clean configuration option for a local filestore type which would be clearly marked as not supported for production environments.

**Comment by mjnagel** [comment]
@Szymongib / @gabrieljackson If you want to assign me to this, I've got a PR that hopefully resolves - https://github.com/mattermost/mattermost-operator/pull/305 - happy to make any modifications needed to get it ready.
