### ISSUE TITLE
Proper way to backup/restore config

### ISSUE THREAD

**Issue by nicolas-goudry** [mattermost/mattermost-operator#260]
#### Summary

Regarding the several different ways config can be handled when using the operator, I’m wondering if there is a proper way to backup the config file? And also restore it?

#### Expected behavior

Provide a way (or several ways) to handle config backup/restore in Operator documentation.

#### Observed behavior

Nothing related to config backup/restore is present in Operator documentation

#### Possible fixes

Configure through environment variables, but this is mostly an alternative solution, not a fix.

It would be great if it was possible to create a `configMap` from a Mattermost configuration file, and then give it to the operator to mount it in the right place inside the pod(s).

**Edit:** as a temporary fix, could we use the `cp` command of `kubectl` to backup and restore config file?

**Comment by nicolas-goudry** [comment]
As of my understanding, there is three ways to handle this:
1. via `configMap`:
    - create a `configMap` with environments variables corresponding to desired configuration
    - set all variables in installation manifest with `valueFrom.configMapKeyRef`
2. via `volumes` and `volumeMounts`:
    - create a `configMap` from `config.json` file
    - create a `volume` from this `configMap`
    - create a `volumeMount` of this `volume`
    - set `MM_CONFIG` environment variable to point to mounted file path
3. via database:
    - set `MM_CONFIG` to database connection string

Please correct me if I’m wrong.

I’ll use the database stored configuration, effectively allowing backup/restore from database backup/restore process. Closing this now (sorry for the useless noise).

**Comment by Szymongib** [comment]
@nicolas-goudry Config in the database is the correct way. Mattermost Operator uses it by default as Operator sets `MM_CONFIG` based on the database configuration. Unless you want to use a different database for config, explicitly setting `MM_CONFIG` is not necesarry.

In regards to config in volumes, I do not think using `ConfigMap` is possible as `ConfigMap` can only be mounted as read-only while config can be changed from System Console. We also do not recommend using volumes with `config.json` as this is not really a tested solution.
