### ISSUE TITLE
Disabling ingress still requires `ingress.host`

### ISSUE THREAD

**Issue by mjnagel** [mattermost/mattermost-operator#261]
#### Summary

The new `ingress.enabled` spec does allow users to disable ingress but it seems like the `ingress.host` value in the spec is used for much more than just the ingress. Disabling ingress without providing an "accurate" value to `ingress.host` causes a number of issues.

#### Steps to reproduce
1. Deploy the operator.
2. Deploy a Mattermost resource with `ingress.enabled` set to false and nothing set under `ingress.host` or `ingressName`.
3. Attempt to navigate to the UI via alternative means (i.e. port-forward or using a service mesh ingress).
4. You should see the UI load a single white screen, with some errors in the browser console.

#### Expected behavior
Ingress should be able to be fully disabled with the UI still working.

#### Observed behavior (that appears unintentional)
Ingress is able to be disabled, but unless you provide an `ingress.host` the UI does not function.

#### Possible fixes

I'm not 100% sure but I suspect it is due to a line [here](https://github.com/mattermost/mattermost-operator/blob/master/pkg/mattermost/mattermost.go#L310) where it is used for the siteUrl - which [affects things in the `config.json`](https://github.com/mattermost/mattermost-operator/blob/master/pkg/mattermost/env_var.go#L9).

Assuming this is the spot that causes the issue, this is clearly a needed variable/config to set. Perhaps the solution is to do a number of things:
1. A new `spec.siteURL` (name/place wherever it makes sense) that is used to populate the `config.json` when available, but defaults to `ingress.host` when not set.
2. Error handling for the operator to reflect this flow ^. Since the ingress was made optional the operator should perform some validation that the siteURL is populated with a value otherwise users can deploy, pods will go to running, but the UI will be unusable.
3. Better document this (maybe not needed if you add a new `siteUrl` value). Currently examples mention that [ingressName is required](https://github.com/mattermost/mattermost-operator/blob/master/docs/examples/mattermost_full.yaml#L17), but only when using an ingress.

While there is a workaround, I think the naming of the values in spec could get confusing and at minimum this should be documented.

**Comment by Szymongib** [comment]
Thanks for reporting the issue, that is definitely a bug.

Interestingly enough the side does load for me but the issue happens after login. Looking at the code it must have been an issue before too when using `useServiceLoadBalancer` and leaving `ingressName` empty. 

I think for now we can set `SiteURL` to empty if the ingress host is not provided, that should make Mattermost work and display the info for the administrator to set `SiteURL` manually in the System Console. As it is possible to set it as env var I do not think we want to introduce another field.

For visibility, the workaround is to set it with an environment variable:
```yaml
...
spec:
  mattermostEnv:
    - name: "MM_SERVICESETTINGS_SITEURL"
      value: https://your_mm.com
...
```

**Comment by mjnagel** [comment]
Thanks for resolving this so quick and providing extra insight into the issue and workaround available. Agreed - better to set it with an ENV than add a new spec value for it.
