### ISSUE TITLE
Operator image validation check failing with sidecar

### ISSUE THREAD

**Issue by mjnagel** [mattermost/mattermost-operator#279]
#### Summary

In summary, when using an injected sidecar with Mattermost and the operator the "image validation health check" could erroneously print that the wrong image is being used, depending on the container order.

#### Steps to reproduce

Deploy the operator + something that will inject a sidecar to pods, in the first container position. In my case I was using Istio when I ran into this issue. Deploy a `Mattermost` CR and watch as it reconciles. The pod should come to healthy with 2/2 containers running but when you check the CR status it will show as "reconciling". Going a step further, check the operator logs and you will see:
```
time="2022-05-13T17:03:48Z" level=info msg="[opr.controllers.Mattermost.health-check] mattermost pod mattermost-xyz is running incorrect image" Request.Name=mattermost Request.Namespace=mattermost
```

#### Expected behavior

I would expect that the operator identifies and checks against the mattermost container, regardless of container order / existing sidecars.

#### Observed behavior

The first container in the pod is always checked, and when a sidecar is present as that first container the health check errors.

#### Possible fixes

The problematic line is [here](https://github.com/mattermost/mattermost-operator/blob/e8b4210eec235426f46d4384d54517e0da542eb5/pkg/mattermost/healthcheck/health_check.go#L68) where the operator checks the first container (`containers[0]`) image.

The fix in my mind would be to have this line instead check a specific container, potentially checking by name since the name seems to be a [variable we could access](https://github.com/mattermost/mattermost-operator/blob/e8b4210eec235426f46d4384d54517e0da542eb5/pkg/mattermost/mattermost.go#L391) (also hardcoded to "mattermost" if I'm not mistaken).

**Comment by Szymongib** [comment]
Thanks for reporting @mjnagel! 

It definitely looks like a bug.

**Comment by mjnagel** [comment]
@Szymongib I got a PR up #280 but I was running into issues with the tests failing. Any guidance on whether I took the wrong approach or what might be happening would be appreciated! The only way I could get it to work was by checking for an empty container name (what the test seems to return).

**Comment by Szymongib** [comment]
I saw the PR, thanks for the fix! 

Just added some suggestions there, let me know if it does not solve the issue.
