### ISSUE TITLE
mattermost-operator does not provide appropriate configuration for securityContext in mattermost deploymets.

### ISSUE THREAD

**Issue by frjaraur** [mattermost/mattermost-operator#286]
#### Summary
Although mattermost-operator deployment via chart allows securityContext configuration, it is not applied to upstream mattermost installations.
I reviewed CRD definition and it does not appear a securityContext key to configure this secure behavior, therefore mattermost installations fail on secure environments (Pod Security Policies enabled not allowing root containers/specify runAs user). This just appears for special initContainers.

#### Steps to reproduce

Deploy the mattermost-operator and create a new mattermost instance.

#### Expected behavior
I expect to be able to specify the securityContext key for upstream mattermost instances created using mattermost-operator.

#### Observed behavior (that appears unintentional)
CreateContainerConfigError arraise as soon as you create a new mattermost instance due to not being able to especify RunAs user key and image defined user is not represented by its ID.

Editing created deployment manually works just by adding requiredsecurityContext configuration, but first it is required to change ownerReferences's controller key to false to disable the management of this resource by the mattermost-operator.

#### Possible fixes
Add securityContext option for being able to configure Kubernetes environment security for both, mattermost-operator and upstream created mattermost instances using it.

**Comment by frjaraur** [comment]
Sorry, I forgot that neither mattermost-operator nor mattermost instances provide securityContext configurations, I did myself for mattermost operator but it should be added also to mattermost deployments.

**Comment by Szymongib** [comment]
Hey @frjaraur, thanks for reporting, this came up in the past, and I think we should add it to Mattermost CR. 

For now, there exist a workaround with use of `resourcePatch`, you can find the details here https://community.mattermost.com/core/pl/dricyco3sbn85kacom55mq9zey

**Comment by Szymongib** [comment]
From the linked thread, you can set it by adding to Mattermost resource:
```yaml
  resourcePatch:
    deployment:
      patch: '[{"op":"add","path":"/spec/template/spec/initContainers/0/securityContext","value":{"runAsUser": 1337}}]'
```

Operator needs to be at in version 1.17+ and CRDs need to match this version.

**Comment by frjaraur** [comment]
Thanks, but it seems it will work for initial containers only or did you just post an example?

**Comment by Szymongib** [comment]
Ah, yeah, that is just example copied straight from the channel. It should be possible to adjust it according to the needs.

**Comment by Szymongib** [comment]
We would like to add a native support for `securityContext` therefore reopening this.
