### ISSUE TITLE
how to launch a command at start up

### ISSUE THREAD

**Issue by sarce666** [mattermost/mattermost-operator#287]
hello 

i d like to launch a mmctl command at startup
how could i implement it in my mattermost deployement ?

in the apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
i cannot add command there ?

thanks

**Comment by gabrieljackson** [comment]
@sarce666, we are going to close this for now. If you still have a reason for wanting to run a custom startup command please let us know.
