### ISSUE TITLE
Add version upgrade to e2e external test

### ISSUE THREAD

**Issue by Szymongib** [mattermost/mattermost-operator#306]
#### Summary

With have e2e test working with "external" database and filestore. It is currently very simplistic, just spawning new instance and waiting for it to be stable.

https://github.com/mattermost/mattermost-operator/blob/master/test/e2e-external/external_db_filestore_test.go#L45-L64

We can extend this test with a Mattermost version upgrade.

The test should:
- Spin up Mattermost and wait for it to become stable.
- Update Mattermost version.
- Wait for instance to be stable again.
- Assert that deployment image was successfully updated.

**Comment by aerokite** [comment]
I will take this. Please assign me

**Comment by gabrieljackson** [comment]
Thanks @aerokite!

**Comment by aerokite** [comment]
what is expected here?

with Mattermost Version update, Server Version should be updated, right?
But, external DB & filestore will not be affected.

**Comment by Szymongib** [comment]
> with Mattermost Version update, Server Version should be updated, right?
But, external DB & filestore will not be affected.

Yes, that is correct. Basically we want to extend [the test](https://github.com/mattermost/mattermost-operator/blob/master/test/e2e-external/external_db_filestore_test.go#L16) to update this version https://github.com/mattermost/mattermost-operator/blob/master/apis/mattermost/v1beta1/mattermost_types.go#L40.

**Comment by aerokite** [comment]
Understood, but this test already exists [here](https://github.com/mattermost/mattermost-operator/blob/master/test/e2e/mattermost_test.go#L58).

Do you want similar test for e2e external?

**Comment by Szymongib** [comment]
Yes. The other test is working with MySQL and MinIO operators and we eventually want to get rid of those, therefore we want to start migrating a bunch of those tests to new framework based on external DB and filestore.
