### ISSUE TITLE
Add e2e external test for sizes and resource constraints

### ISSUE THREAD

**Issue by Szymongib** [mattermost/mattermost-operator#307]
#### Summary
We can add e2e test using the "external" DB and filestore to verify that sizing and resource constraint logic works correctly.

The test can:
- Spin up Mattermost instance with specified size.
- Assert that it starts correctly and that replicas and resources are set based on size.
- Assert that size value was removed.
- Manually change resource constraints.
- Assert that resources where adjusted and instance is stable.
- Set a different size on Mattermost instance.
- Again assert that resources were adjusted properly.

**Comment by aerokite** [comment]
I will take it
