### ISSUE TITLE
Kubernetes won't pull down the right mattermost-operator version

### ISSUE THREAD

**Issue by MSaurus** [mattermost/mattermost-operator#90]
When I install mattermost-operator on a kubernetes cluster that already have pulled down the image before, it won't get the latest version of mattermost-operator. In [this documentation file](https://github.com/mattermost/mattermost-operator/blob/master/docs/mattermost-operator/mattermost-operator.yaml) you use both `image: mattermost/mattermost-operator:latest` and `imagePullPolicy: IfNotPresent`. 

This results in that kubernetes will pull down the image just the first time a user run this yaml file. Then you make an update to mattermost-operator and I want that update. So if the user then run this yaml again, then kubernetes will use the cache of mattermost-operator image instead of pulling down the latest because the imagePullPolicy says it should only pull down the image if the image doesn't exists in the cache. Which it does, because it's the same name and the same tag. 

Proposed solution would be to start versioning the mattermost-operator image and put that in the image tag. Then Kubernetes won't use the cache if the image is updated. A user can also decide which version they want to use.

Another solution would be to remove the `imagePullPolicy` and still use latest as the image tag. Kubernetes would then use `Always` as the pull policy. However this will make Kubernetes to always pull down the image from docker hub, even if the image hasn't been changed.

**Comment by jozuenoon** [comment]
Method with `latest` would work, but versioning is more pragmatic and feels like good idea :+1:

**Comment by gabrieljackson** [comment]
Thank you for the feedback @MSaurus!

We are aware that we currently have that configuration of `latest` + `IfNotPresent` in this manifest file. This is partly due to the operator being very much in flux and also due to some cross referencing of the manifests here with those used in the [cloud server](https://github.com/mattermost/mattermost-cloud).

That said, we can definitely improve this and will change this manifest's behavior asap.

**Comment by MSaurus** [comment]
Thanks! If there is something I can help with just let me know :)

**Comment by cpanato** [comment]
@MSaurus you should not use the latest tag in your production system, please use a specific tag instead

the way we set the latest +  IfNotPresent is more for the CI tests.
if you are using for testing only you can change the manifest to change the imagePullPolicy

Closing this, feel free to open a new issue if still have problems.
